[config]
# Matugen strictly requires this block to exist at the top.
reload_apps = false

[templates.quickshell]
# If the tilde (~) ever gives you trouble, replace it with /home/yourusername/
input_path = "~/.config/hypr/scripts/quickshell/colors.json.template"
output_path = "/tmp/qs_colors.json"

[templates.zen]
input_path = "~/.config/matugen/templates/zen.css"
output_path = "~/.config/zen/matugen.css"

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar.css"
output_path = "~/.config/waybar/matugen.css"
post_hook = "pkill -USR2 waybar"

[templates.rofi]
input_path = "~/.config/matugen/templates/rofi.rasi"
output_path = "~/.config/rofi/colors.rasi"

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland-colors.conf"
output_path = "~/.config/hypr/matugen-colors.conf"
post_hook = "sleep 0.05 && hyprctl reload"

[templates.vesktop]
input_path = '~/.config/matugen/templates/vesktop.css'
output_path = '~/.config/vesktop/themes/matugen.css'