hl.config({ autogenerated = false })

hl.config({
	input = {
		kb_layout = "de",
		follow_mouse = 1,
		touchpad = { natural_scroll = true },
	},
	gesture = {
		workspace_swipe = true,
		workspace_swipe_fingers = 3,
	},
	misc = {
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
	},
})

hl.exec_once("zsh ~/.config/hypr/scripts/session_start.sh")
hl.exec_once("zsh jetbrains-toolbox")

require("displays")
require("theme")
require("keybinds")
